version: "3"
services:
  mysql:
    container_name: mysql-container
    image: mysql:8
    restart: always
    volumes:
      - ./local_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: fastapi_crud
      MYSQL_ROOT_PASSWORD: my-password
    ports:
      - "3306:3306"
  api:
    container_name: api-container
    image: python:3.10.7-buster
    working_dir: /usr/src/fastapi-crud
    command: bash -c "pip install -r requirements.txt && gunicorn app.main.server:app --workers 3 --worker-class uvicorn.workers.UvicornWorker --bind :8000"
    restart: always
    volumes:
      - ./app:/usr/src/fastapi-crud/app/
      - ./requirements.txt:/usr/src/fastapi-crud/requirements.txt
    ports:
      - "8000:8000"
    links:
      - mysql
